version: "3"
services:
  consul:
    image: autopilotpattern/consul:0.7.3r39
    restart: always
    dns:
      - 127.0.0.1
    labels:
      - triton.cns.services=consul
    ports:
      - "8500:8500"
    command: >
      /usr/local/bin/containerpilot
    environment:
      - CONSUL_DEV=1
    network_mode: host
  frontend:
    image: d0cker/frontend:6.2.0
    environment:
      - CONSUL=consul
      - PORT=10001
    labels:
      kompose.service.type: nodeport
    expose:
      - 10001
      - 9090
    ports:
      - "10001:10001"
    network_mode: host
  serializer:
    image: d0cker/serializer:6.5.0
    env_file:
      - .env
    environment:
      - CONSUL=consul
      - INFLUXDB_USER=root
      - INFLUXDB_PWD=root123
      - PORT=10000
    expose:
      - 9090
      - 10000
    ports:
      - "10000:10000"
    network_mode: host
  prometheus:
    image: autopilotpattern/prometheus:1.7.1-r20
    restart: always
    ports:
      - "9090:9090"
    env_file:
      - .env
    dns:
      - 127.0.0.1
    network_mode: host
  nats:
    image: autopilotpattern/nats:0.9.6-r1.0.0
    restart: always
    ports:
      - 8222
    env_file:
      - .env
    network_mode: host
  redis:
    image: redis
    expose:
      - 6379
    restart: always
  gateway:
    image: d0cker/gateway:4.0.0
    ports:
      - "8001:8001"
    env_file:
      - .env
    restart: always
    network_mode: host
  influxdb:
    image: autopilotpattern/influxdb:1.1.1
    ports:
      - "8086:8086"
      - "8083:8083"
    restart: always
    labels:
      kompose.service.type: nodeport
    env_file:
      - .env
    environment:
      - ADMIN_USER=root
      - INFLUXDB_INIT_PWD=root123
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_REPORTING_DISABLED=true
      - INFLUXDB_DATA_QUERY_LOG_ENABLED=false
      - INFLUXDB_HTTP_LOG_ENABLED=false
      - INFLUXDB_CONTINUOUS_QUERIES_LOG_ENABLED=false
    network_mode: host
  smartthings:
    image: d0cker/smartthings:8.2.0
    labels:
      - triton.cns.services=smartthings
    ports:
      - "80:80"
    env_file:
      - .env
    environment:
      - FAKE_MODE=true
      - PORT=80
    restart: always
    network_mode: host
  humidity:
    image: d0cker/sensor:4.2.0
    env_file:
      - .env
    environment:
      - SENSOR_TYPE=humidity
      - CONSUL=consul
      - NATS_USER=ruser
      - NATS_PASSWORD=password
    restart: always
  motion:
    image: d0cker/sensor:4.2.0
    env_file:
      - .env
    environment:
      - SENSOR_TYPE=motion
    restart: always
  temperature:
    image: d0cker/sensor:4.2.0
    env_file:
      - .env
    environment:
      - SENSOR_TYPE=temperature
    restart: always
