apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
    triton.cns.services: consul
  creationTimestamp: null
  labels:
    io.kompose.service: consul
  name: consul
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: consul
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
        triton.cns.services: consul
      creationTimestamp: null
      labels:
        io.kompose.service: consul
    spec:
      containers:
      - args:
        - /usr/local/bin/containerpilot
        env:
        - name: CONSUL_DEV
          value: "1"
        image: autopilotpattern/consul:0.7.3r39
        imagePullPolicy: ""
        name: consul
        ports:
        - containerPort: 8500
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
