apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: loadbalancer
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  ports:
  - name: "10001"
    port: 10001
    targetPort: 10001
  selector:
    io.kompose.service: frontend
  type: LoadBalancer
status:
  loadBalancer: {}
