apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: serializer
  name: serializer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: serializer
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: serializer
    spec:
      containers:
      - env:
        - name: ADMIN_USER
          valueFrom:
            configMapKeyRef:
              key: ADMIN_USER
              name: env
        - name: CONSUL
          valueFrom:
            configMapKeyRef:
              key: CONSUL
              name: env
        - name: CONSUL_AGENT
          valueFrom:
            configMapKeyRef:
              key: CONSUL_AGENT
              name: env
        - name: INFLUXDB_PWD
          value: root123
        - name: INFLUXDB_USER
          value: root
        - name: NATS_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: NATS_PASSWORD
              name: env
        - name: NATS_USER
          valueFrom:
            configMapKeyRef:
              key: NATS_USER
              name: env
        - name: PORT
          value: "10000"
        image: d0cker/serializer:6.5.0
        imagePullPolicy: ""
        name: serializer
        ports:
        - containerPort: 10000
        - containerPort: 9090
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
