apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
    triton.cns.services: smartthings
  creationTimestamp: null
  labels:
    io.kompose.service: smartthings
  name: smartthings
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: smartthings
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
        triton.cns.services: smartthings
      creationTimestamp: null
      labels:
        io.kompose.service: smartthings
    spec:
      containers:
      - env:
        - name: ADMIN_USER
          valueFrom:
            configMapKeyRef:
              key: ADMIN_USER
              name: env
        - name: CONSUL
          valueFrom:
            configMapKeyRef:
              key: CONSUL
              name: env
        - name: CONSUL_AGENT
          valueFrom:
            configMapKeyRef:
              key: CONSUL_AGENT
              name: env
        - name: FAKE_MODE
          value: "true"
        - name: NATS_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: NATS_PASSWORD
              name: env
        - name: NATS_USER
          valueFrom:
            configMapKeyRef:
              key: NATS_USER
              name: env
        - name: PORT
          value: "80"
        image: d0cker/smartthings:8.2.0
        imagePullPolicy: ""
        name: smartthings
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
