apiVersion: apps/v1
kind: Deployment
metadata:
  name:  smarthings
  namespace: default
  labels:
    app:  smarthings
spec:
  selector:
    matchLabels:
      app: smarthings
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  smarthings
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  smarthings
        image:  d0cker/smartthings:8.2.0
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        env:
        - name: CONSUL_AGENT
          value: "1"
        - name: NATS_USER
          value: "ruser"
        - name: NATS_PASSWORD
          value: "password"
        - name: ADMIN_USER
          value: "root"
        - name: CONSUL
          value: "consul"
        - name : FAKE_MODE
          value: "true"
        - name: PORT
          value: "80"
        ports:
        - containerPort:  80
          name:  smarthings
      restartPolicy: Always