apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: nodeport
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: influxdb
  name: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: influxdb
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.service.type: nodeport
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: influxdb
    spec:
      containers:
      - env:
        - name: ADMIN_USER
          valueFrom:
            configMapKeyRef:
              key: ADMIN_USER
              name: env
        - name: CONSUL
          valueFrom:
            configMapKeyRef:
              key: CONSUL
              name: env
        - name: CONSUL_AGENT
          valueFrom:
            configMapKeyRef:
              key: CONSUL_AGENT
              name: env
        - name: INFLUXDB_ADMIN_ENABLED
          value: "true"
        - name: INFLUXDB_CONTINUOUS_QUERIES_LOG_ENABLED
          value: "false"
        - name: INFLUXDB_DATA_QUERY_LOG_ENABLED
          value: "false"
        - name: INFLUXDB_HTTP_LOG_ENABLED
          value: "false"
        - name: INFLUXDB_INIT_PWD
          value: root123
        - name: INFLUXDB_REPORTING_DISABLED
          value: "true"
        - name: NATS_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: NATS_PASSWORD
              name: env
        - name: NATS_USER
          valueFrom:
            configMapKeyRef:
              key: NATS_USER
              name: env
        image: autopilotpattern/influxdb:1.1.1
        imagePullPolicy: ""
        name: influxdb
        ports:
        - containerPort: 8086
        - containerPort: 8083
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
