apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: nodeport
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: influxdb
  name: influxdb
spec:
  ports:
  - name: "8086"
    port: 8086
    targetPort: 8086
  - name: "8083"
    port: 8083
    targetPort: 8083
  selector:
    io.kompose.service: influxdb
  type: NodePort
status:
  loadBalancer: {}
