apiVersion: apps/v1
kind: Deployment
metadata:
  name:  influxdb
  namespace: default
  labels:
    app:  influxdb
spec:
  selector:
    matchLabels:
      app: influxdb
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  influxdb
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  influxdb
        image:  autopilotpattern/influxdb:1.1.1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        
        
        env:
        - name: ADMIN_USER
          value: "root"
        - name: INFLUXDB_INIT_PWD
          value: "root123"
        - name: INFLUXDB_ADMIN_ENABLED
          value: "true"
        - name: INFLUXDB_REPORTING_DISABLED
          value: "true"
        - name: INFLUXDB_DATA_QUERY_LOG_ENABLED
          value: "false"
        - name: INFLUXDB_HTTP_LOG_ENABLED
          value: "false"
        - name: INFLUXDB_CONTINUOUS_QUERIES_LOG_ENABLED
          value: "false" 
        - name: CONSUL_AGENT
          value: "1"
        - name: NATS_USER
          value: "ruser"
        - name: NATS_PASSWORD
          value: "password"
        - name: ADMIN_USER
          value: "root"
        - name: CONSUL
          value: "consul"
        ports:
        - containerPort:  8086
          name:  influxdb
        
      restartPolicy: Always