apiVersion: apps/v1
kind: Deployment
metadata:
  name:  gateway
  namespace: default
  labels:
    app:  gateway
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  gateway
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  gateway
        image:  d0cker/gateway:4.0.0
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        
        
        env:
          - name: CONSUL_AGENT
            value: "1"
          - name: NATS_USER
            value: "ruser"
          - name: NATS_PASSWORD
            value: "password"
          - name: ADMIN_USER
            value: "root"
          - name: CONSUL
            value: "consul"
        ports:
        - containerPort:  8001
          name:  gateway
        
      restartPolicy: Always