apiVersion: apps/v1
kind: Deployment
metadata:
  name:  nats
  namespace: default
  labels:
    app:  nats
spec:
  selector:
    matchLabels:
      app: nats
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  nats
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  nats
        image:  autopilotpattern/nats:0.9.6-r1.0.0
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        env:
          - name: CONSUL_AGENT
            value: "1"
          - name: NATS_USER
            value: "ruser"
          - name: NATS_PASSWORD
            value: "password"
          - name: ADMIN_USER
            value: "root"
          - name: CONSUL
            value: "consul"
        ports:
        - containerPort:  80
          name:  nats
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
      volumes:
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
      restartPolicy: Always