apiVersion: apps/v1
kind: Deployment
metadata:
  name:  consul
  namespace: default
  labels:
    app:  consul
spec:
  selector:
    matchLabels:
      app: consul
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  consul
    spec:
      containers:
      - name:  consul
        image:  autopilotpattern/consul:0.7.3r39
        command:
          - "/usr/local/bin/containerpilot"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        env:
        - name: CONSUL_DEV
          value: "1"
        ports:
        - containerPort:  8500
 
      restartPolicy: Always