apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: default
spec:
  selector:
    app: gateway
  type: NodePort
  ports:
  - name: gateway
    port: 8001
    targetPort: 8001
    protocol: TCP