apiVersion: v1
kind: Service
metadata:
  name: smartthings
  namespace: default
spec:
  selector:
    app: smartthings
  type: NodePort
  ports:
  - name: smartthings
    port: 80
    targetPort: 80
    protocol: TCP