apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: default
spec:
  selector:
    app: frontend
  ports:
  - name: frontend
    port: 10001
    targetPort: 10001
    protocol: TCP
    