apiVersion: v1
kind: Service
metadata:
  name: consul
  namespace: default
spec:
  selector:
    app: consul
  type: NodePort
  ports:
  - name: consul
    port: 8500
    targetPort: 8500
    protocol: TCP