apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: default
spec:
  selector:
    app: frontend
  type: NodePort
  ports:
  - name: frontend
    port: 9090
    targetPort: 10001
    protocol: TCP
    nodePort: 30000