apiVersion: v1
kind: Service
metadata:
  name: nats
  namespace: default
spec:
  selector:
    app: nats
  type: NodePort
  ports:
  - name: nats
    port: 8222 
    targetPort: 8222 
    protocol: TCP